hash-format = "sha256"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "80cb330a91a726c3d1403e39f34e4af75f60f1d0ca050efce54b4ab4f837913d"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "266515169b28342abd5ebdf3e44fc34bffe7c57029ffd0822cc47a876a3b2d39"
metafile = true

[[files]]
file = "mods/anvil-balance.pw.toml"
hash = "c061df2eadb18c8986ba57f1b61081b37d9f294594024d8c09f446152d61ec72"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6cf760735d24d9ec5c43565d0debfd66e4784495ccfd22ec64706a412dae1a92"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "b29835680379e9f5f639ee51000686afa24844ae0b3499c737703a00e8bcf2ce"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "2f16c335deb5abd76290b7468e28df1dd8fcb59038cf679a36c11c8bb77130c7"
metafile = true

[[files]]
file = "mods/beehivetooltips.pw.toml"
hash = "22c4f745f7b8599bfdfd9df482e3145611c01e55d40d9385d60c40867574e7b1"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "a6717b228791d860a2c59d325e3f5cf4eeef45d497d4989f887c7df7a6a9a7f6"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "ac17f2db4aa44cc093d16889d448d17990ebd3f3843e569c9c80871a9be47c05"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
hash = "23ee96dfca63c20bea124fc0ae4ae4e29d68f786a6dbd91311e8c6323819ce54"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "12388b826b567055528c3f79f65b86fbff632436d9c9edd6958537598ae74930"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "98a57ab297037c2ddcc29a1c0114d0ff4a127d5e5193556b416b0ac81c7162b0"
metafile = true

[[files]]
file = "mods/block-runner-forge.pw.toml"
hash = "06421b9a764da73db33d8239d811466637879472bd5c1639c1c923d156cca041"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "1bec051f2a7db3226a03c99a4d9fb8d25d088d2378e65bec104f9ea2f07db091"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "cab3b9ffbc7c2fa5cd28d41ba53b3b6b96ef288b31a01a72f1451270180b7922"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "fa0ad0d273105eb80b1451373b56c6ee679408dd14e8db99351db9f6149c516b"
metafile = true

[[files]]
file = "mods/catalogue.pw.toml"
hash = "432fdc4ecbd021736333cb68abacc14ce7db418b54811ae8dbe62a75d535f9f3"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "c98f38003e1928b623d69bd4db617879c5e27b8fbdc9b17a9b7fe52241644e62"
metafile = true

[[files]]
file = "mods/clean-swing-through-grass.pw.toml"
hash = "c2401bbd1410839d2ced6d944631132dcfde2b76fe8ae8b4ae2fbf68c725c07d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b95522dafe82dde9b8b123451092a5534f000f036ce446bf22813ee3c1434c5b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "12cbf3bcce53737cb7de3b26372537c219cb70d898fe3577307bccbedc8e265e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "ae7709d679b4035ebc95e985d56c38b54fc09f8b3ea6c5bc9fd316631082ec32"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "59ada98de37ebbedf431062792208c91bcfec37a07e78a1cc6c5d3bc09437094"
metafile = true

[[files]]
file = "mods/compact-help-command.pw.toml"
hash = "c3a7720011c8df28d6bce9e962d7904ff4b6dd817d63b691a8fae795728c05f5"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "401670e18a9a3245fef841c73552a58c58fd830df38e158bf76915089cab3fd1"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "9105fbd45fb875e8b5c419899372fed43ece46ff178cc97132bd9b21860db7c6"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "3f4f8d75126e546b6c900a7149ae795ff1f297566961759c726ec6a9baa38cb6"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "21b77c50359ef9252199ce3f862b76dfad938a6807e8bee8e3fe0e5c39c87d53"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "f043324e03ba1f8465029efca52378aa1c673eeb3b47aef0241629318adcfd72"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
hash = "c98fe0eb527cfcfecdb3619de7f1573472461865f48081b65717df5b08d3d20f"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "5e0f9eac1cf40e1b4e34909f29130a64bc70c2686609c6e5b449e5680d34bfc4"
metafile = true

[[files]]
file = "mods/drawers-tooltip.pw.toml"
hash = "06c52f4d43b5ea3b91c0983821e1710de231986200af1a1c68ee3c0828293599"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "ac247cb7316e37bc07535e47c5fa0a5c0a4773501c6994d006a93e111096b1df"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "cda10d789303589cecd0ade82f81d97378df21c84c576b7f3e0d1ea33b6b6443"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "2dff16922361e691f2bf733d17d16c82d035c8b079b1d161ff24961f469cdf96"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f9a348f9cef7b44116093c080ad539d383508ae493db16a47e858a19de81d13f"
metafile = true

[[files]]
file = "mods/equipment-compare.pw.toml"
hash = "5f02a1d44446f78810c33829774e5e15e7b34884f3846dc19b195b4ac4225300"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "9c1524daba2d5f5da1d8bb7f7e6108a6f0fbca3ff485a074aa81bad1540babab"
metafile = true

[[files]]
file = "mods/flib.pw.toml"
hash = "8c5f92a603d7c1beb6074ac8883559c805641446727aa3505c298cb85e864e34"
metafile = true

[[files]]
file = "mods/food-effect-tooltips-forge.pw.toml"
hash = "fd1b8327a3ef816b0210d2438cde8bf28344fa6dec314fc192f60cbea8c7f9ba"
metafile = true

[[files]]
file = "mods/framed-compacting-drawers.pw.toml"
hash = "89ae0e948f4d0fba4cf9f3f44e55c1fdf090b1a9027d85b06314697a8edb7b22"
metafile = true

[[files]]
file = "mods/full-grown-crop-marker.pw.toml"
hash = "aeefed7d40094b9891eba424af9d5bc2b48beea0000153fc24b65ffbf7ab328d"
metafile = true

[[files]]
file = "mods/geophilic-reforged.pw.toml"
hash = "7ce2b362661bf4082f1b2598435bc4430b55550c392972b35948fa22e4d38ed5"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "b2ca6e21336f992b963587491b2f004f756f741159300d1ca9ce7088703983e9"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "a367be99e4b5dd7f8226a2df2bbcccc375cb700c9ba8360db9977c3774f604d3"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
hash = "f984385586820346804385968e4dfc7683cfac4504508bea4e53573e8cf48dbd"
metafile = true

[[files]]
file = "mods/inventory-sorter.pw.toml"
hash = "af2d91b55f75f082a2b6227c73c5494fe3b3056317c153644079d151cd051e0d"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "95acd8e8f86c7e6accb4d7381e8899e2091c84d5d3dcb975d2969b8e6884ea74"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "5fb1637fb710ea1965aff9bfb74988394241261929456d2d81387decf253af54"
metafile = true

[[files]]
file = "mods/jadecolonies.pw.toml"
hash = "0fc4e716d3602722fc4a987398d4a59d1811621d9e7e11fce929c8ae62be45bf"
metafile = true

[[files]]
file = "mods/jea.pw.toml"
hash = "3ece46760548042a81191c675dfe65a31d9cf1f9fa6e90b61c600b6c0b1c9682"
metafile = true

[[files]]
file = "mods/jei-integration.pw.toml"
hash = "f4470434ceef2caeccbc108b09aa2fc3226d20517106760fe9505bfac3faa311"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "ac4c1ea81e0afeb18800e5ea574e961684c445e1c37f3b13c4146111577358db"
metafile = true

[[files]]
file = "mods/jepp.pw.toml"
hash = "8aec26d6737831e0e257c88d3b081732b991bc375c3d961350b8e0dc13246077"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "53ca8b877cfde113c1a7c27360e15092249a646f67a8c85ea31be38b935a94fb"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "90e01bd3cd96f32e89bdb3224dc034bfcc83274b348e511f38bb7ad9ef60ddd2"
metafile = true

[[files]]
file = "mods/just-enough-archaeology.pw.toml"
hash = "b3e6ed9d1a0ed69dc0853efbc9f21a64cc236057d602f3b83ee81694ec2842af"
metafile = true

[[files]]
file = "mods/just-enough-beacons-reforged.pw.toml"
hash = "43d5593a0c1563483bc84a7e67e62354e45fc9b98b7e3dfb463bdc48604c2917"
metafile = true

[[files]]
file = "mods/just-enough-calculation.pw.toml"
hash = "4c6a3faef4a4a217dc312e417833ef7db8c239ae279884eb3ff5b298d14be953"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "d56ff0e3513e79e1352a15b15b26f24f37d815c0ea5fc176c4778b4369bca938"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "a9dfada6dd05e2736d283a979d532fd2ac703501a6d69e765fa4f19ede1320d7"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "80cd2b13b61ec26b40649b4f728211907b748abff34190aae6c0feb0aed77f41"
metafile = true

[[files]]
file = "mods/just-enough-sculk-sensor.pw.toml"
hash = "4825ad40ab33ca934a2849ff220bedd81ceeeec67efd8c65119966a51c5811b7"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "c5922c3de09200de975722dda565ad0aea3c38ebd24ec814d49c1006c1294e5c"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "7c95103b8fffc96d97b00e710c11ca72225c0bd5e166ff5593c7d5bf31e0f4ce"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "062548dfa16195ac6d9b59b85f6f7f7a97ead9c1eb8227d98063d723a5652b1f"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "165a4b9cdf6df7bca36d9ec260019c127ad5fbb36ae86e5ea4ce4ec3ff915c88"
metafile = true

[[files]]
file = "mods/libx.pw.toml"
hash = "53c90bad9008b937df61b567e0d1fff96ca6597e2536a8530843d194ad3efab1"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "db4827dca60c01ad2f40bbbd18711c1f4bfa09759287662f53018c150019ed09"
metafile = true

[[files]]
file = "mods/mod-name-tooltip.pw.toml"
hash = "fd62c8c7e2828c7445efeee50afbecce7f28c382db86c21d54af7ad280364b4c"
metafile = true

[[files]]
file = "mods/moderately-enough-effect-descriptions-meed-a-jeed-addon.pw.toml"
hash = "1438efdd90ec72bec66e14af4b9d5bc4b0f555a7f8475cbac0b1f12474f015a2"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "eaf123915c95f7c351144255d92f4cba9c9d04d095ad8058769eee4b4a626bb4"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "047a3caf847654446259d363ab2a63f8d33a4cb764adf6615f48d0c7a10d7d97"
metafile = true

[[files]]
file = "mods/ocean-floor-clay-sand-and-dirt.pw.toml"
hash = "17817a7d88fcca1cb66272bc4dacadefa688d304c22f3a0fc51ec748ef228415"
metafile = true

[[files]]
file = "mods/passable-foliage.pw.toml"
hash = "f075f88db75e41b8c298f8bb7c4ed640ffe3e34c251d4d121bd91d36aa352faf"
metafile = true

[[files]]
file = "mods/peacefulsurface.pw.toml"
hash = "0c252103357bd28595e8b1e5bcd03df3b8ce3fed46666cf43c3b7a561563930e"
metafile = true

[[files]]
file = "mods/portal-linking-compass.pw.toml"
hash = "aefe27cdcca3386df072045b9b9518f75ac48725d058622f90f41792ec2ec829"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "4865bdb37d0107a71653005fb2f71d8da70cc31f0352131f330b126be3cbc95f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a9b28c6fb53af2a369169af0e7a43d57fb240fbf71eaa41beeba487830e9c9c5"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "e619e3ad1d70da863e6facb7d455dd2a9ab949a57841185beb45581e99accd2a"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "09a28833265812c7319cd2662151ef2d4be9d754ad25645c83824f636c9ca7e6"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "e2812edc57c959105ca229046c7d3be2e97c4414887bb94387602c9d00ad0381"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "d5b77300a457d40c1d9d1ba6529c4b450ca1fd053d5095b1cf889e5b79b899c3"
metafile = true

[[files]]
file = "mods/spotiforge.pw.toml"
hash = "e2f1458ab461a151683b1b799a24c284731a4d535683f45af705d97685b0d479"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "51b505f42ccf1b6857792afd13368f81f98bb0ab1e3dba394d7574daa7607df9"
metafile = true

[[files]]
file = "mods/storage-racks.pw.toml"
hash = "f923f4e1a62ed27f0052f1a14f870907eb09d60b5f8c1fe75db628cf7ab5e1b3"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "61f603c9781cfea579e4f8a365c0ab5ad2a2f68ee8750ae604a4cd4df9d0f545"
metafile = true

[[files]]
file = "mods/stylecolonies.pw.toml"
hash = "6e71940cc39f5e9438ebdc3e8ac47a25b47507164729ecb37cff032b4d4a5b4f"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "ff9d5c6fea4e3a4540698bbdc2c557e18fbcf58bcc7c2de49bd5aa789b165c54"
metafile = true

[[files]]
file = "mods/tan-huge-trees.pw.toml"
hash = "c1876213f6fbd454757690414e73787a2cfc945787aa70cdbc114d11abb90f30"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "35deaaab3405d590dad7cfa2a3ac390143df99e8d8361c19a826c0afa44323c2"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "75aeaf4a98c98fafa39907317fc9a95904b33f6908702eb2df1224d587876a9b"
metafile = true

[[files]]
file = "mods/treasuredistance.pw.toml"
hash = "0386e88642287b3d9539d9e6f14b25f7908423a0bb7e87cd60c112c21d024772"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "8490488a491a29d33398d96341050eff53142ac80ada86118309a3a96f830060"
metafile = true

[[files]]
file = "mods/vanilla-tools.pw.toml"
hash = "5629b9b438cfb374931e7139aeda7b588bd9577cd78c2fb26a42e700fb5de6a5"
metafile = true

[[files]]
file = "mods/waterphysics.pw.toml"
hash = "220068e20461d71aec82b4c693a17419f67798485ff381d7ef3bfe62e3b72a6c"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "1d9fa3f5d831284d6e428622277441d38f7615102b609ed53f2cfa3b8700f599"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "9fde4b16604dd74fecac6737154877b486766dbe66e158d2a3c8efed1bc3ac5f"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "d5e5106ec9b4a1d086c9d9643b2451746b9876bf1e7f2eac5e19ee37c2db46e6"
metafile = true

[[files]]
file = "resourcepacks/hd-font-inconsolata.pw.toml"
hash = "36d1633d9bc9974dd8a6b08dc47dde3bb784d61cd82a13d34f0ae236217a7fb8"
metafile = true

[[files]]
file = "resourcepacks/xray-ultimate-1-11-compatible.pw.toml"
hash = "49b2aea7885162b26e3829039aa756dc2869b43bb7ae75fb729a38f90288daa5"
metafile = true

[[files]]
file = "shaderpacks/vanilla-plus-shader.pw.toml"
hash = "27e72b90e3d059ed3bc654ebec957ddc87f4443aba70a956a0cb14d53daecf74"
metafile = true
