name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db21cf623623f05e7393fe31bb31a348923cd47b5ab8da6c70fd16275bed01aa"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
