name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b19a3102ac6196cc30fd7c28f65451d76a4ce0a03c2aad1268046641224991b"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
