hash-format = "sha256"

[[files]]
file = "config/shutdowner.json"
hash = "0438b7e34fbd8418c09d96875ebc9b2d6dbe9e06723e57326c29cf85c3feebcc"

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "5cd33a09220c4bfbacb3cbd3fb9a077ce301dad1ba642f89582625d1c3f3c166"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "51a2f092f1089d78871db5bf8fab51d79d3882e62337f88e9d70f7abca8668a2"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "bc5dedb9dc7b9b1b824acb4a6aec4c8f88e9a19ef298fc87faef0d7cfa4821d6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5d9a21e91b78633977a1f5635bd0f335acfec60743dc991a63fa09bee3eed5aa"
metafile = true

[[files]]
file = "mods/automatic-tool-swap.pw.toml"
hash = "2ae3b592d80a7c5632840febb3c04cd869f5cf399cd90bf8af040151b3e6abfa"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie-reloaded.pw.toml"
hash = "34345ab4645293657a3dcf1113b233b99c832f50bce016b2458060245dd76024"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5355ffd96b79ac184f7de73443376a3cb4e4ea70977972b707e1128377a41a0a"
metafile = true

[[files]]
file = "mods/better-chunk-loading-forge-fabric.pw.toml"
hash = "2b1a0d15180397de8e13abd4f674efb8c7e5ac605f029605440081d7057d6f34"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
hash = "a93632e5fdbbd44f9cb8b795a9fbd387e573a51c75174020092b432759a6e86a"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "40d577414f97ac95d37a82bf00d4159e60b6b57c22b38711fe14576369648b2e"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
hash = "c5248b3fd00dbdc689b13d05bb49d129e07a2871be3297078735220b60a10452"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "21d4e3a5deb3553be8c3a6190d26b6c6771750f969adf80c02c82321c3433129"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "c9f9b8c28d08acd45b86dd2df243b02d3924d23d05fb454f67cae3550d993918"
metafile = true

[[files]]
file = "mods/cerbons-better-beacons.pw.toml"
hash = "fd4a3885b3f22fb1f887baf1e2fee1bfb7ce3242b80d9d3c271012fbbde104a3"
metafile = true

[[files]]
file = "mods/clean-swing-through-grass.pw.toml"
hash = "56238686f8c444a4352d43cfd1333403ab0e2037cfc8064dca777a7dc8803b09"
metafile = true

[[files]]
file = "mods/clean-tooltips.pw.toml"
hash = "4bca7d9914640d54b1b7da116aa493d499fb0d17dd6e4786db1c494b734e8cba"
metafile = true

[[files]]
file = "mods/clickable-advancements.pw.toml"
hash = "f117d2b419b7ceafe727b43a47a95cb11dd52c60d0fda886ac2cca4c5f594951"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "3e4d7a730c9e735865d787b2e96598ef02412336662d75e2a59d4e7099fbedf0"
metafile = true

[[files]]
file = "mods/climate-rivers.pw.toml"
hash = "5293ffa38dae10610d144d797998ffe7fcee7c6f4538f632904819e6c3b589c1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "938460cd7dec76ba9cedea030cb93030675f3f2645b4375a862eac4e05d00e08"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "89326c55b4db63820520f43dcb74a1da6c96ee29c73ca6c3b2cbe7cc1e4519ac"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "f5ff7e3186f3937c72f09cc277a109266da8df3355fdc32d9794c306770b699f"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "80b2f9d3391865f5a8ec7c55540b03373a7b21b1dd8d5ad7ede4825fb1926cbf"
metafile = true

[[files]]
file = "mods/compact-help-command.pw.toml"
hash = "0c2f13eca2ea553e0ff6d018b5ddf29b4d729d9f127ca6602c351cc28d1df43b"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "fa425f55efd993bcf8d74aa10b6111bdf74590f78ab9ad06cea39ecc32479791"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e47ee073cb5c6f639b58769553c653b6cc8a8ebff27b8c55b12739417179d6af"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "5e717707b7bd82497435adbd69b99a66b6aea96b766dcc330a8a62741d3a0c89"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "21a440631ff26d7ffa681d8919467cb6002472a9b93ac64e92ecb787059d0a10"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
hash = "417a688e1944d712cae05359060838ede0a7d1d4996ea34d6cf48e92d7a4954a"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "50e18f592c1c5a2c34dfefcb8fe9af60ba1cf578e49130cac126ce451f4fd08a"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "af3778b20091aea3fe473ae573d67e5191833918997dd8979ddecb98fb20f5d8"
metafile = true

[[files]]
file = "mods/dynamic-view.pw.toml"
hash = "6733ddeedc3327a03af6c8f2d9106c10912477a1764fa1d9334a58e096a5eaa3"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "49c2dee455e7cf0944160f16bf10f9a238424877751ac7d1d76550e7937fdab9"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "583c1141fafde94ddce4a88911938349c905c423f49c8ad53de6a7e1333852f5"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "34f51a5709b728d8e4796346aa5f98e284c72293aaad957d724e0808d9a23e2c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "a24a49f3a46b5a9ff19d335f9cc747854380fa828f8c57e3f63468ebf6f180ff"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "6c08d09ab872c01970f3e63d86dc4860ccfa5ea5e415f68a0f64f492e2ad1901"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
hash = "1628f2c4c13d74978235c1793a5c1d6c5fe8f600c8aa27340f7a973879033372"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "2866a793ec1c19f649f2268a608c1ef927b7ceba2458ba71451177fbc8d05a7f"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "e18b9b65e339c1c1d237e2820e33dce00666e0554437453b4ef744fff94e48c0"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "11363eb33ff94633e824001c5f342a17466a5c196f966a07c25dfc89bf6aa540"
metafile = true

[[files]]
file = "mods/ftb-quests-forge.pw.toml"
hash = "7600be99030303cf4943446c4bff980b20c23bc1e046d8f8c903cf850c66e500"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "27af24df4ce419660646846f75d69061985ad7ba308d9b921baea7d02f09e003"
metafile = true

[[files]]
file = "mods/hud-compass.pw.toml"
hash = "0524db5121f443bea31b41c72b93ec091d20d0679ab6539be61428e2cd883431"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
hash = "530ac48cc9ac1c3eb1001550ace2b3a52f6225127aba050bb9bcf2297653d3cb"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "460d84569844d3ea98e7b772439271d228df720ee4ed8a2cd4ee3dd3e8afb263"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "f1682ad6ff7d06c7b8814d65129fa33f473fdb39d6a69584057f470b135cf4e4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "509cc6e0dda334bcbc1d398639428ac6958df717964faee83cac7af710bbcec1"
metafile = true

[[files]]
file = "mods/jadecolonies.pw.toml"
hash = "ed2a6adf4aa6fdfbd625b533ccead3d8f5a5def44c98a8a15675d3717d9e9874"
metafile = true

[[files]]
file = "mods/jea.pw.toml"
hash = "b1ec0ffc493da280cbeeaa65ebe299f3a0b57cd47bef94c846d946e661778885"
metafile = true

[[files]]
file = "mods/jei-integration-reborn.pw.toml"
hash = "fd9e21b1adc521eb56789049a5d080a3e62ef2d8974f081b32e7b3e659b7a11c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "143398b8c538da7240bb322e3da80c0b078b46bc6d20cc77a871165b6b009670"
metafile = true

[[files]]
file = "mods/jepp.pw.toml"
hash = "1e42cfae2afc3725f61302b68f5610e3c200ac65f4583a4318fb6f9b0629ece0"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "9d8624f68e5b76444d0c23a72b61d8b68f6dcf7177aaff14908c0f92d0a30063"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "0808595c763b7909fb3c1fb2ca04ce0a7d347bcc3cdee4b04cc1d4dfc7658e3e"
metafile = true

[[files]]
file = "mods/just-enough-archaeology.pw.toml"
hash = "bc75a48fde194b477886a32800366a71b86342804be87d6816d612610a0afaf8"
metafile = true

[[files]]
file = "mods/just-enough-beacons-reforged.pw.toml"
hash = "32a72a708163f4c70c7da8d4c65eea069a86f0500d85e17dfe3211f5709da38f"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "3b9badad425e0b4ca69ee9d9c9e4f8235dbb38ad98ce85335e6fd223977b7ba8"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "ab2979801607eabcf44052674c4b681cba4d7562840b96314ba86764ca4445ca"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "1bb74549680f250ceccaa33e229c9aac5c84c1361b292358831a143a9cb2e123"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "b7f72a32af4febbdff54fbac07d79bfcd005d6c9c4d5b90eb20f895a8370ef12"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "41bde62eee7559ef9307e5bd4ad469aeeaf536bc1a7a5eb30157625e4be7dd49"
metafile = true

[[files]]
file = "mods/libx.pw.toml"
hash = "ecc6ae10d56ed2c0cfab30d16e84d51e79f0900ca2bc7953f77049a6f9e67393"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "ca181b55fce6d5a258621d1d02a107b0510e6964b53a648c8c5fb7edd3f63c1f"
metafile = true

[[files]]
file = "mods/moderately-enough-effect-descriptions-meed.pw.toml"
hash = "7014a4052c63a833b45550db0983a71b69a837fd456194381964e408b77bd821"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "91ae5a2b29890b5f21d4be76fdacca363ca4245bf81ff778737017dc453c942f"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "7354bcc08a9bab26bbaef05ce253cb5828e371ab0af82b5a8a82c4424701ec8b"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "12718584f31b4875e2087083ad9d83ca89861b9a0c3d279f737a845a6f3c46cc"
metafile = true

[[files]]
file = "mods/new-paper-doll.pw.toml"
hash = "6d4b0139cddf6e6b6422e6e9836bd1bed1845c0582310ffb8fb98f7de80fc8c5"
metafile = true

[[files]]
file = "mods/packed-up-backpacks.pw.toml"
hash = "202e17118691a8aeaf95847d25e415e2ec61d562e2486e6fe1fc215e0b92739e"
metafile = true

[[files]]
file = "mods/peacefulsurface.pw.toml"
hash = "5467133b585a425cb6815a3bcf9b16448706f221f4ca8bfe991bb162efadec4f"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "df42633b7c3999b4f083bbf157e00e7f78625b6e33c225037f97cc53e30a3ace"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "0f97422c22459b070a0c47fa69343c65c964087f6d23a9a379ff86865767c9de"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
hash = "95df32778981016c59cd3f1b9181c3e13ee008ebf0536fefdc79159e171b6f2b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6d0943d51a8894141fd80423f81dfde1c24d53c54258f9bcd42d1ba3651583b3"
metafile = true

[[files]]
file = "mods/shutdowner.pw.toml"
hash = "1597f0dbc2574e2e4f3007fc0984f8816a84e2c0f4de6b230308c17937a25632"
metafile = true

[[files]]
file = "mods/smithing-template-viewer.pw.toml"
hash = "4ab6122fa5449cfa64a3b957f3f7d236f439cd17ec874ec0edad86a9c162e4fd"
metafile = true

[[files]]
file = "mods/storage-racks.pw.toml"
hash = "9238e063d5f06857b2bc686213ff108ca36bdf83a89e3117d88ece0551060097"
metafile = true

[[files]]
file = "mods/structure-compass.pw.toml"
hash = "0cc052687955d3aa1a2b2bb982cec2e5ff5f4ff3d826ad4dbf3ec31e5460c8cd"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "5860b993ed1865df4bc326e86c24d723dc167b158524996a714f9f61b221c271"
metafile = true

[[files]]
file = "mods/stylecolonies.pw.toml"
hash = "6f3c67ff277cfb48dda1321c7d191800a03d5ddf3db98a8ef0ccda4b11a51918"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "47b922642a474e267f4cbcea8f1604ee4ff10f054df477eeefa631c715d727cb"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "37d57aa0005758aa930defaba1d50b1f65bd5dfd4a5770d19ff6a6cf5d7ed2f1"
metafile = true

[[files]]
file = "mods/terrablender-neoforge.pw.toml"
hash = "445a5f29c74bcb632f3d981527db14b785e7a4acd1dadc515615cec5b1444391"
metafile = true

[[files]]
file = "mods/theovergrowth.pw.toml"
hash = "efa44f7bb00b18db6543294b5a457d024688a9347731c3aafd726a914c077266"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "f366eb17066c00e4b5dc63b6974f29d7bd6d047fab20e29e9cebe5998d74c476"
metafile = true

[[files]]
file = "mods/travelers-compass.pw.toml"
hash = "51c9b69a8fbd7da6f98585146124b91c609e83df196c2d01a896ec6258bcf202"
metafile = true

[[files]]
file = "mods/treasuredistance.pw.toml"
hash = "f28c84b4db9f619e7b4a7391886b38c5ca725483e361dc2267a03ab75ae1a4ea"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "6b24969ac885f4c6449fbbfdca64b055c316bc612fa601b89728f0910da922ab"
metafile = true

[[files]]
file = "mods/vanilla-tools.pw.toml"
hash = "3353efefd84d3dde9365b4dde1229566be7f3378b94aacfc64d3db0af0640ceb"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "0ff50a0130e1c2e51ca1b9f869bf084305c3c330ba50c042785a8b0d49a508f7"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "bb4b4b93915c279ccdd00f48345300dddf71ab839c5e518cad89621253ad63a9"
metafile = true

[[files]]
file = "mods/weather-settings.pw.toml"
hash = "798b8c34f6e184fcb8017fee1f1fb415e641ca08862ecf1674e683ada9556c93"
metafile = true

[[files]]
file = "mods/william-wythers-overhauled-overworld.pw.toml"
hash = "a710789a8cd63806987ebd3f753de60d8d35d07e3643e28e1188c1a5c370817b"
metafile = true

[[files]]
file = "resourcepacks/borderless-glass-no-optifine-needed.pw.toml"
hash = "66f4dba2de6d6e5eeafc5ed0df4527eae764a409f09ddc34a86bb8022e8fd837"
metafile = true

[[files]]
file = "resourcepacks/clear-glass-pack.pw.toml"
hash = "68ad4da86c941125b0faa2ff20737e9093e0bd1e0350a97fee26c517f180ab60"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "6d7d75b35907b563e2fdbe4740f51c34d83e332e5829ed3defb6b035815421c3"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "23bcbde144eaa409988ef49890c16f67d43985e95267799e98d8e354fa3a297a"
metafile = true

[[files]]
file = "resourcepacks/hd-font-inconsolata.pw.toml"
hash = "0f0a4f056abbf091dc5838c2557ea2477cc9d4c9ba9623ffe9be118bf14afd92"
metafile = true
