hash-format = "sha256"

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "5cd33a09220c4bfbacb3cbd3fb9a077ce301dad1ba642f89582625d1c3f3c166"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "db026135a8a23b2b660ebbfa8a85d06b26249305b2612bc2fab930e252100890"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4ca8b963965342aafdfe251e5306259eb9cf459d43e46d9695974dcff01465aa"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/automatic-tool-swap.pw.toml"
hash = "2ab2402ca9faa13e6380baae7ba9c12cbe77472010ac6c685978d14658c8f88a"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie-reloaded.pw.toml"
hash = "c3233ab72a796b7a0fcea7fa22b88ef5ee0512daf3c767be4f88e6e4f30881b0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "32220d2f0275dd71f089742921c86c8964186a8d9610434f53f67f2e459c2ef2"
metafile = true

[[files]]
file = "mods/better-chunk-loading-forge-fabric.pw.toml"
hash = "07e756eec150953e1da73adbee0c1d4d79cd9c48bc9c78ae4d3591e7097b45f2"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
hash = "422e9de11c4996c14a0a907cfe627428c7c52e9ee55c8da0193236038da02680"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "c2fd5f53d8ee32c2f7a69959bf4fed00ac7e5ab3568b2bcf5c970a9b3b66969a"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
hash = "bfc87776286283ea7571375f8941fa98073172d0906a40fa2bb9400b74cf2d00"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "64a7bbf0eaf41a1b4d0270ec4255554a25ac278f04f0ae9e110050b42464370f"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "1cb3db95dbf424de74a4572994d7b32fc8560dc31e0495d10825f195b2103462"
metafile = true

[[files]]
file = "mods/cerbons-better-beacons.pw.toml"
hash = "5513d17f0ad17bcc2a5cf347b670d7c321aaa780686cac1dfa6c0730e6fb088a"
metafile = true

[[files]]
file = "mods/clean-swing-through-grass.pw.toml"
hash = "69968d3337983555531273604549745ad124bc95e19363f69cb4d1e41f47a980"
metafile = true

[[files]]
file = "mods/clean-tooltips.pw.toml"
hash = "41cca1c89e237f070a57cf01da0c7fd9c43d74fe7548efd09f57c1219899ea9b"
metafile = true

[[files]]
file = "mods/clickable-advancements.pw.toml"
hash = "7b5c86be25546796eb891e4444e0478aaf93d3515e57df4fd20cdda0daa05a52"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "1f41272b5cdabe73dc343bdb89eb9993c82df611a18182dcbc7107a46b7458bb"
metafile = true

[[files]]
file = "mods/climate-rivers.pw.toml"
hash = "56191b31aa0c189768ac79c5afe06f249c930d39fd317273a98520478f0d06ab"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "42c658ecafe98b802924b2a8a10bfc995d743efdc2cf7a1965274d302380f1e7"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "531d3dd3deb7479e3fd1496a7c2db8606bc7affa33fc57eccddc9904c0ac559e"
metafile = true

[[files]]
file = "mods/compact-help-command.pw.toml"
hash = "78363fcbc3b669a97a019501998e70d1efb3ced8798a028b36acebb77ea77b3f"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "ccf9e64814aea3a7c29689a9f2509002976428bdb798119cb32cdbd655456a07"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "92d8711662b4e3fd42a57254571aca9f0b33a10bb7492a8fba59b22e78f688e6"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "539513ed35cebfaa099397dde2d1936d38489c8685e96a902211f60cecee82c4"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
hash = "b210a17a51e1143ce69dd2adc9f4d4ff7c13775721a2067be6ca6712cb76fd71"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "560677900d746ef9c35cb48d1e51dfc8abcc188b3d390fde1dc3458f9c800057"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "13af7707844b2af1b04c8e95ad86016cd45e89a8d10b9a6aba1caee55e6991fe"
metafile = true

[[files]]
file = "mods/dynamic-view.pw.toml"
hash = "d691dae878d32f7b64daafd1ded247acf8a20b34228a1ed06c6320357b6c2672"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "f3ae4c6cea3288a0c0d1c6f5c1a18992f45c38559908e84c774c9f49ad91b74e"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0042336abc94bae434faa534e9c2e1d1e477d5f984f9f993d92aa856143f3379"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "9389b4311f93eaea1e627ee793137607370e2e782836e03ee6ca49a41cc7b06d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "06e87d3cc5ee6a1f467160d2cb8e416f42aaa2c4271adb380c2672f4f4cac9c8"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "35bad9f01671b5b4284ad547dab6635b2a029980c88d82007690e9232a5cb420"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
hash = "3138c13c61cca083b45ba2598c2407194ba5ea16d2a610968527eafa021c4635"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "e70c20bf24819da470d25d8cfe9cd07d2fc4ace4de942e7bcd38f7a674a24b6c"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48172cddf0c2014e76b1d06bc9fd84297019610cd57d4099f4cf4c1b263ae328"
metafile = true

[[files]]
file = "mods/ftb-quests-forge.pw.toml"
hash = "4c815298380c86c4dffb14f4db3ff6159a1935629cfda47b769550d66585f16b"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "ec32ed4418310d282eedba77f3e08898037e2a1b7ed904ba9d00971d0aa4b4c9"
metafile = true

[[files]]
file = "mods/hud-compass.pw.toml"
hash = "44ae848196fbbca713b21f24efdf1f5285614d21335a5131790eb2e9faa96576"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
hash = "3fd3c85f4ac889ee87857be7c64e883efe6cb06de73ab7babf07521977912353"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "11caa0f933a60871f90c04af165bdc7c2ec96c9ec2b3045f5ac1cd88cfba76aa"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "49e1313f8a664f6f53c6045a1b9499787aaf4d9d014e4decc376c7c6fe0b3a68"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6b3f722168fa57e23fca5441d9b74a11194d9252625d6bf0898c4d212f99380a"
metafile = true

[[files]]
file = "mods/jadecolonies.pw.toml"
hash = "94f69e149cc3604cb09197de52e6d07731d56cca3d10388ccb9dbfe8b36ee76e"
metafile = true

[[files]]
file = "mods/jea.pw.toml"
hash = "c26d3d0fc2d1e0fa23ec74f1b4d473ee09fcc98406c059af726aa051af9ee9ce"
metafile = true

[[files]]
file = "mods/jei-integration-reborn.pw.toml"
hash = "456e0331a1812e791210831c96f99439960e02647afb3210ffa8152ef9b75320"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "8b4e6f98185fa77d721a3950ae708d633622e41fd6a303e8c1e4cbb1105d429f"
metafile = true

[[files]]
file = "mods/jepp.pw.toml"
hash = "67525a62684355cafa36d863e289d03a200f59f03f63f61fd18bfcce553419a4"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "20202d3155a9c99848a2aa34648766d909538346a6f996d284e6fa2e1569e39e"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "448c3e93e0cd1231c129313a82fa2820644f4ebdaa78346bb283dc29acbe9976"
metafile = true

[[files]]
file = "mods/just-enough-archaeology.pw.toml"
hash = "12858c5f2b34a2b53b45eb681cf0922e9658bfba547c9c677ae8e1e6c8f8908f"
metafile = true

[[files]]
file = "mods/just-enough-beacons-reforged.pw.toml"
hash = "b44eba29adb71baf6b47c3c494ad6cf4b19974dfe2af4a0c6d06e0b7e3aa71d0"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "3d2944c2ffc2c06911b6ecec062d375e76e3c9cee238196a6fa996017a49971d"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "fc938f58fda1614b0bd4c88546b4c37c660777600b7b63479f1022f90b16f407"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "480364ee4530bebdb3c4538dd30458e084a061bc3c4b42fb23a2ed3de2e16302"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "0a4cccfaef6e590d95d2a07d32b0c8ec133b50bc669f802f754abdc04277b30c"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7fbe3225c134e823a07f3aecedace39fe866f327671ecca928f134399b94008d"
metafile = true

[[files]]
file = "mods/libx.pw.toml"
hash = "94c73f3e5f65947247491081494b5aef5bcdd937984def52d640670e7610450d"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "5ce6ef06d45a72aa63cd763e67943a79b04251d7fa69c5daad2a2da439b3f935"
metafile = true

[[files]]
file = "mods/moderately-enough-effect-descriptions-meed.pw.toml"
hash = "4fd644527b02b9d5e52ef63a047f9f73005e07d242d3c79cb3ab785291913727"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "4e82a688470620148b1bbcd609438af5bc5fe76cef22c56962c8e8d8f4f2f901"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "bc9449306cb2c32f16347779291d68e5fba67f85d7aca04b4b9cc1c033ec4083"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "b5be9033308bb88924ddbc0eb95011a6ad1674099f0db976ab5e05a28afc4971"
metafile = true

[[files]]
file = "mods/new-paper-doll.pw.toml"
hash = "e544f57b1f23f4fba3b43a461aa9add6e9e8cce0078d587f9a8dfb71b9fdc22c"
metafile = true

[[files]]
file = "mods/packed-up-backpacks.pw.toml"
hash = "eecc04e5ccb1ef7b93ad5eb286153ffa672093a23a816fe9c34d37924500214a"
metafile = true

[[files]]
file = "mods/peacefulsurface.pw.toml"
hash = "71966cd516e73dd6c5641231313fddf0576cc3afbd8736f5c1f45834cd4d9721"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "eab2f56ff9135b3b7253ea5a73deae2f887e2876f5f0432936044a6e926937b4"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "804736be3ded2a6f89f44522b88d82636209ed203c234ea34b6d6ffdd9ecee54"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
hash = "63798d5d5dce18e8558415ee791f0928e12ee2bb54ee342f4b81b58f523e3cb2"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/shutdowner.pw.toml"
hash = "6068aaf4cc6ca742a92779ede7a021bd9c90175d7cc0d7be8250c971f9b2aebb"
metafile = true

[[files]]
file = "mods/smithing-template-viewer.pw.toml"
hash = "0d5a805b094f0bf0936c7de227621dd8571a09c24659fb19dd1f4806a909a47b"
metafile = true

[[files]]
file = "mods/storage-racks.pw.toml"
hash = "a57ffb8934ba047e0405a36c4e8d69c5330185150aae93fc0c4795874be561f0"
metafile = true

[[files]]
file = "mods/structure-compass.pw.toml"
hash = "7087b995c2b326e6fc45fa1afef0de53f20585468753fc3e6bd0b9a220d09657"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "8f857c83c1097e6a0538f71979fb5271f94299a87cbdc68d2a197b57fc101970"
metafile = true

[[files]]
file = "mods/stylecolonies.pw.toml"
hash = "eab08b2dbb1f940da66339c914bee02f24d15419d6345f9bee436755170409c8"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "2e42245826ce70d4ad673addb0e5244da388841f1484f03ee5a9426ee33b2229"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "130f04ff53fcd4cdb82fd357ae36a8fd7ef16f8f3de38d348dec6e7ba24d866b"
metafile = true

[[files]]
file = "mods/terrablender-neoforge.pw.toml"
hash = "d77e4dc337b6090358c1ef01b0f99a8357e5279443e0e23e511de1be865c01c9"
metafile = true

[[files]]
file = "mods/theovergrowth.pw.toml"
hash = "26b5c8a35d19ca75004b4d21836f321f2d09bedd78438ff2548eb7a41f891688"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "a7074e8e499d34f5ce633dbd33f818e376dd1941ec5b1d97a33acd019df69b5a"
metafile = true

[[files]]
file = "mods/travelers-compass.pw.toml"
hash = "0f9db8cfcc09b5ea48b26b57ee03231e8608117d9f227150769c1e88e818aa74"
metafile = true

[[files]]
file = "mods/treasuredistance.pw.toml"
hash = "0d081ab462011674df91efe39094588305c40915c79fa13c63ff9302e9ccd775"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "f0770e8df6212a00fcea3dcd72bdcaa344fa745593abc867b7e499fb493556b6"
metafile = true

[[files]]
file = "mods/vanilla-tools.pw.toml"
hash = "6a9517c9117dcb876b267e453c3470513284469eac38fd669864cc1b5dceb930"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "f28ceb27bc3ed0a9825de1f853d177b69495deab9128aa05694616e4504ddb52"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "ea16c0d61b7753a2fb969bdf00e3a3c9f5f0c0fd2d658668e379ad3c48e7d61f"
metafile = true

[[files]]
file = "mods/weather-settings.pw.toml"
hash = "c0f1178dedf5f03cbdb3a2bb713368c4079f63487d42ebb8252b4286ac8c76a7"
metafile = true

[[files]]
file = "mods/william-wythers-overhauled-overworld.pw.toml"
hash = "63d4a6aefa8b8231a03e6d7d4af9866673bae0b839a28964a522598cec44845c"
metafile = true

[[files]]
file = "resourcepacks/borderless-glass-no-optifine-needed.pw.toml"
hash = "37a691e53437fbbe9896947e06e050e6eef3c9a06e592c39dc3c827ade1cd8a5"
metafile = true

[[files]]
file = "resourcepacks/clear-glass-pack.pw.toml"
hash = "2ac36144100131d2b582455b95bfa1ebb652fc96b0b241820917c4d31e3db95e"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "09468b987b5825de6fb7d22b00a579bb9aee7ff80dc0010540c1c51d3c7cd591"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "fbcacaccd3eedf13c88488e8c274e3b042f70dd9381a98333b32c122d7c8a785"
metafile = true

[[files]]
file = "resourcepacks/hd-font-inconsolata.pw.toml"
hash = "736798e92b3fb089d3d05f7b1c1452bfc2a63350c76269de18a256399c9d72ee"
metafile = true
