name = "HarleyColonies"
author = "Alan Young"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a03a7ea115ca4f50aede932db0adf1e181a3ed1d1d0a1a189728e82e8a437639"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
