name = "HarleyColonies"
author = "Alan Young"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d9cbedc76e773418ce5623b0104f9b704d5406560f068b7b7dbe01c5b1f6b4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
