name = "HarleyColonies"
author = "Alan Young"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132737735b28bb382f5a07cba661908423bd30acce54c1188af8530178a3e83a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
